language: node_js


node_js:
  - "4.0"
  - "4.1"
  - "5"

before_install:
  - npm set progress=false

env:
  - CXX=g++-4.8

addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

before_script:
  - psql -c 'create database ulysses;' -U postgres

services:
  - redis-server

sudo: false

notifications:
  email:
    on_success: always
    on_failure: always
