language: node_js


node_js:
  - "4.0"
  - "4.1"

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq rethinkdb

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database ulysses;' -U postgres

services:
  - redis-server


sudo: required
dist: trusty

notifications:
  email:
    on_success: always
    on_failure: always
